<a href="/login/area">Zurück</a><br>
<div style="position: absolute">
<span>Nutzer Online</span>
<div id="onlineArea" style="background-color: greenyellow;width:200px;height:300px">
</div>
</div>
<span id="loadNewMessage" style="position: absolute;left: 600px;top: 60px">Neue Nachrichten Abrufen</span>
<div  id="newMessageDiv" style="position: absolute;left: 600px;background-color: cornflowerblue">
<tab><span>Neue Nachrichten:</span> <span id="showNumber">0</span></tab>
</div>

<div id="messanger" title="Messanger">
<div id="verlauf" style="width: 80%;height: 50%;margin-top: 20px;margin-left: 40px;margin-right: 40px;background-color: #dcdcdc"></div>
<div><textarea id="writenNewMessage" style="resize:none;position: relative;bottom: -30px;left: 40px;width: 80%;height: 110px"></textarea></div>
<button id="sendMessageButton"style="width: 80%; height: 30px;margin-left: 40px;position: relative; bottom: -32px">Senden</button>

</div>
<script>
$(document).ready(function(){

    var myVar = setInterval(function(){searchOnlineUser()}, 5000);

    $( "#messanger" ).dialog({
        width: 450,
        height: 500,
        autoOpen: false,
        show: {
            effect: "blind",
            duration: 100
        },
        hide: {
            effect: "explode",
            duration: 100

        }
    });


    $('#loadNewMessage').click(function(){
        getNewMessages();
    })
    function searchOnlineUser(){
        $.post('/login/chatroom/controllUser', {data: {
        }}).success(function(r){
            var string = ' ';
            for(var i = 0;i<r['counter'];i++){

                string += '<span class="aktiveUserForChat" id="User_'+r[i]['id']+'">'
                string += r[i]['vorname']
                string += ' '
                string += r[i]['nachname']
                string += '</span><br>'
            }
            $('#onlineArea').html(string);
            startClickEvent();
        })
    }

    function startClickEvent(){
        $('.aktiveUserForChat').click(function(){
            var idString = $(this).prop('id');
            var id = idString.split('_');
            var r = [];
            r['id'] = 0;
            r['empfaengerId'] = id[1];
            $( "#messanger" ).dialog( "open" );
            $('#sendMessageButton').unbind('click');
            $('#sendMessageButton').click(function(){
                setNewMessages(r);
            })


        })

    }
    function getNewMessages(){
        $.post('/login/chatroom/NewMessage', {data: {
        }}).success(function(r){
            $('#showNumber').html(r['count']);
            if(r['count']>0){
                $('#showNumber').css('background-color','yellow');
                showVorschauNewMessage(r);
            } else {
                $('#showNumber').css('background-color','cornflowerblue');
            }
        });
    }
    function showVorschauNewMessage(r){
        var string = '<div id="newMessagesShowDiV" style="display:none">'
        for(var i=0;i<r['count'];i++){
            string += '<p id="message_'+r[i]['id']+'"class="newUnreadMessage">'
            string +=   r[i]['vorname'] + ' ' + r[i]['nachname'];
            string += '</p>'
        }
        string += '</div>';
        $('#showNumber').append(string);
        openNewMessage();
        $('#newMessageDiv').unbind("click");
        $('#newMessageDiv').click(function(){
            $('#newMessagesShowDiV').toggle();
        })
    }
    function openNewMessage(){
        $('.newUnreadMessage').click(function(){
            var idString = $(this).prop('id');
            var id = idString.split('_');
            $.post('/login/chatroom/getMessage', {data: {
                index: id[1]
            }}).success(function(r){
                var verlaufstring = '<p>';
                verlaufstring += r['vorname'] + ' ' + r['nachname'] + ' : ' + r['message'];
                verlaufstring += '</p>'
                $('#verlauf').html(verlaufstring);
                $( "#messanger" ).dialog( "open" );
                getNewMessages();
                $('#sendMessageButton').unbind('click');
                $('#sendMessageButton').click(function(){
                    setNewMessages(r);
                })

            })

        })
    }
    function setNewMessages(r){
        var oldString = $('#verlauf').html();
        var inputString = $('#writenNewMessage').val();
        var newString = oldString;
        newString += '<p>DU: '+ inputString+'</p>';
        $('#writenNewMessage').val('');
        $('#verlauf').html(newString);
        $.post('/login/chatroom/setMessage', {data: {
            id: r['id'],
            empfaenger: r['empfaengerId'],
            message: inputString
        }})
    }


})
</script>