
<form method="post">
<input type="text" name='login' id="login" placeholder="Login">
<input type="password" name='password' id="password" placeholder="password">
<button type="submit" id="senden" >Anmelden</button>
</form>









<script type="text/javascript">
$(document).ready(function(){
	$("#senden").click(function(){
		$.post('login/controll', {data: {login: $('#login').val(), Password:$('#password').val()}}).success(function(r){
			
			});
	
		})
})
</script>
